name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm --prefix ./frontend install
          npm --prefix ./frontend run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          FACERECOGNITION_BACKEND_URL: ${{ secrets.FACERECOGNITION_BACKEND_URL }}

        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/build
